### PR TITLE
Update to use RawSonarImage image and support EK80 single beam data.

### PR DESCRIPTION
**Pull request by rolker**

### CODE REVIEW

**Comment by CaptKrasno** [comment]
Looks good. I see you added support for all datatypes too!  (I just had uint 16 before).   Thanks.

Were you able to test it with your new sonar driver?

**Comment by CaptKrasno** [comment]
Oooh... Auto gain too! Nice

**Comment by rolker** [comment]
Yeah, I tested with my driver that spits out values in dB as floats so I only tested that it works with DTYPE_FLOAT32.
The auto gain was my quick solutions to handle dBs!

**Comment by CaptKrasno** [comment]
Good enough for me.   I will merge this.  I may make some changes after I update the norbit driver.

-Kris

**Pull request merged**
